from .home_view import *
from .cart_view import *
from .category_view import *
from .order_view import *
from .review_view import *
from .wishlist_view import *
from .coupon_view import *
from .shipment_view import *
from .product_view import *